site_name: recommender-systems
repo_url: https://github.com/nikolaos-mavromatis/recommender-systems
site_url: https://nikolaos-mavromatis.github.io/recommender-systems
site_description: A collection of notebooks and scripts using various recommender system techniques.
site_author: Nikolaos Mavromatis
edit_uri: edit/main/docs/
repo_name: nikolaos-mavromatis/recommender-systems
copyright: Maintained by <a href="https://nikolaos-mavromatis.com">nikolaos-mavromatis</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [recommender_systems]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nikolaos-mavromatis/recommender-systems
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/recommender-systems

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
